services:
  django_crested_myna:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: "django_crested_myna"
    expose:
      - "8000"
    volumes:
      - ./crested_myna:/crested_myna
      - nginx_reverse_proxy_certbot-etc:/etc/letsencrypt
      - nginx_reverse_proxy_certbot-var:/var/lib/letsencrypt
    command: gunicorn crested_myna.wsgi:application --bind 0.0.0.0:8000            
    env_file:
      - .env.prod
    environment:
      - DJANGO_ENV=production
    networks:
      - shared_network
    restart: unless-stopped
volumes:
  nginx_reverse_proxy_certbot-etc:
    external: true
  nginx_reverse_proxy_certbot-var:
    external: true
networks:
  shared_network:
    external: true
