services:
  django_crested_myna:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: "django_crested_myna"
    expose:
      - "8000"
    volumes:
      - crested_myna:/crested_myna
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    command: gunicorn crested_myna.wsgi:application --bind 0.0.0.0:8000            
    env_file:
      - .env.prod
    environment:
      - DJANGO_ENV=production
    networks:
      - shared_network
    restart: unless-stopped
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./webroot:/var/www/certbot
    networks:
      - shared_network
volumes:
  crested_myna:
  certbot-etc:
  certbot-var:
networks:
  shared_network:
    external: true
