services:
  django_crested_myna:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: "django_crested_myna"
    ports:
      - "8000:8000"
    volumes:
      - ./crested_myna:/crested_myna
    command: gunicorn crested_myna.wsgi:application --bind 0.0.0.0:8000            
    env_file:
      - .env.prod
    environment:
      - DJANGO_ENV=production
    networks:
      - shared_network
    restart: unless-stopped
volumes:
  crested_myna:
networks:
  shared_network:
    external: true
