# Generated by Django 5.1.1 on 2024-10-18 21:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ACRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_id', models.CharField(max_length=100)),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('country_code', models.CharField(max_length=2)),
                ('country', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('state_code', models.CharField(max_length=150)),
                ('observation_date', models.DateField()),
                ('year', models.IntegerField(null=True)),
                ('observation_count', models.IntegerField(blank=True, null=True)),
                ('time_observations_started', models.TimeField(null=True)),
                ('duration_minutes', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['country', 'year'],
            },
        ),
    ]
