# Generated by Django 5.1.1 on 2024-11-04 19:06
""" Migration to populate the ACRecord table with the data from the csv file. """

from django.db import migrations
from django.core.management import call_command

def run_command_add_ebird_data(apps, schema_editor):
    """ Command to populate the ACRecord table with the data from the csv file. """
    call_command('populate_database_with_ebird_data')

class Migration(migrations.Migration):
    dependencies = [
        ('data_loading', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(run_command_add_ebird_data),
    ]
