# Generated by Django 5.1.1 on 2024-11-04 19:10

from django.db import migrations
from data_loading.load import run


def save_world_shp_in_database(apps, schema_editor):
    """ Save the world shapefile in the database """
    try:
        run()
        print("\033[92mSuccessfully populated the database with the world shapefile\033[0m")
    except Exception as e:
        print(f"\033[91mError populating the database with the world shapefile: {e}\033[0m")


class Migration(migrations.Migration):

    dependencies = [
        ('data_loading', '0002_add_ebird_data'),
    ]

    operations = [
        migrations.RunPython(
            save_world_shp_in_database
        ),
    ]
