# Generated by Django 5.1.1 on 2024-11-07 18:45
""" SQL PostGis command to populate the simplified countries table
by using ST_Simplify with a 0.01 tolerance.
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_loading', '0004_postgis_make_polygons_valid'),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Populate the simplified countries table

            INSERT INTO data_loading_countrysimplified(name, iso2, simple_geom)
            SELECT
                name,
                iso2,
                ST_Simplify(geom, 0.01) as simple_geom
            FROM data_loading_country;
            """
        )
    ]
