# Generated by Django 5.1.1 on 2024-11-04 20:00

""" SQL command to update the observations_count field in the ACRecord table 
Observations count can be null or NA on ebird data.
However, here the observations count will be replaced by 1 in those cases with null,
because at least one bird was observed to register the record.
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_loading', '0005_postgis_simplify_polygons'),
    ]

    operations = [
        migrations.RunSQL(
            """
            UPDATE data_loading_acrecord
                SET observation_count = 1
            WHERE observation_count IS NULL;
            """
        )
    ]
