# Generated by Django 5.1.1 on 2024-11-04 21:23

""" Series of SQL commands to populate the CountryWithACRecord table
with the data from the Country table and the ACRecord table.
It inserts name, iso2 and geom fields into the CountryWithACRecord table
and updates the total observations events, the total birds count and the
is_exotic fields.
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_loading', '0007_sql_update_point_field_as_geom'),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Insert the countries that have AC records into the CountryWithACRecord table

            INSERT INTO data_loading_countrywithacrecord(name, iso2, geom)
            SELECT DISTINCT ON (ac.country_code) 
                ct.name,
                ac.country_code,
                ct.simple_geom as geom
            FROM data_loading_acrecord ac, data_loading_countrysimplified ct 
            WHERE ct.iso2 = ac.country_code;

            -- Update the total observations events of the bird for each country

            UPDATE data_loading_countrywithacrecord AS ct
            SET tot_observations_events = ac.record_count
            FROM (
                SELECT country_code, COUNT(*) AS record_count
                FROM data_loading_acrecord
                GROUP BY country_code
            ) AS ac
            WHERE ac.country_code = ct.iso2;

            -- Update the total birds count for each country

            UPDATE data_loading_countrywithacrecord AS ct
            SET tot_birds_count = ac.birds_count
            FROM (
                SELECT 
                    SUM(observation_count) AS birds_count,
                    country_code
                FROM data_loading_acrecord
                GROUP BY country_code
            ) AS ac
            WHERE ac.country_code = ct.iso2;

            -- Update the is_exotic field for each country

            UPDATE data_loading_countrywithacrecord AS ct
            SET is_exotic = CASE
                WHEN iso2 NOT IN ('CN', 'MM', 'LA', 'VN') THEN TRUE
                ELSE FALSE
            END;

            """
        )
    ]
