# Generated by Django 5.1.1 on 2024-11-08 20:17
""" SQL command to insert the cities from countries with AC exotic records 
into the CitiesACExotic table. """

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_loading', '0009_postgis_join_cities_layers'),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Insert the cities from countries with AC records into the CitiesACExotic table
            INSERT INTO data_loading_citiesacexotic(city_name, population, iso2, lat, lon, geom)
            SELECT
                city.city_name,
                city.population,
                city.iso2,
                city.lat,
                city.lon,
                city.geom
            FROM data_loading_cities city, data_loading_countrywithacrecord ct 
            WHERE city.iso2 = ct.iso2 AND city.iso2 not in ('CN', 'MM', 'LA', 'VN');
            """
        )
    ]
