# Generated by Django 5.1.1 on 2024-11-09 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_loading', '0011_postgis_variable_buffer_according_population'),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Create a view with the urban observations
            CREATE OR REPLACE VIEW urban_observations_view AS
            SELECT 
                sum(ac.observation_count) as urban_obs,
                ct.iso2
            FROM data_loading_acrecord ac, data_loading_buffercitiesexotic4326 ct
            WHERE ST_CONTAINS(ct.geom, ac.geom) = TRUE AND ac.country_code = ct.iso2
            group by ct.iso2;

            -- Create a view with the total observations
            CREATE OR REPLACE VIEW tot_observations_view AS
            SELECT 
                sum(tot_birds_count) as tot_obs,
                iso2
            FROM data_loading_countrywithacrecord
            group by iso2;

            -- Create a view with the rural observations
            CREATE OR REPLACE VIEW rural_observations_view as
            SELECT 
                (tot.tot_obs - urb.urban_obs) as rural_obs,
                tot.iso2
            FROM tot_observations_view tot, urban_observations_view urb
            WHERE tot.iso2 = urb.iso2;
            
            -- Create a view with the habitat observations
            CREATE OR REPLACE VIEW habitat_observations_view AS
            SELECT 
                tot.iso2,
                tot.tot_obs,
                COALESCE(urb.urban_obs, 0) as urban_obs,
                COALESCE(rur.rural_obs, 0) as rural_obs
            FROM tot_observations_view tot
            LEFT JOIN urban_observations_view urb ON tot.iso2 = urb.iso2
            LEFT JOIN rural_observations_view rur ON tot.iso2 = rur.iso2;
            
            -- Insert the views into the tables
            INSERT INTO data_loading_urbanruralobservations (urban_obs, rural_obs, tot_obs, iso2)
            SELECT 
                urban_obs,
                rural_obs,
                tot_obs,
                iso2
            FROM habitat_observations_view;
            """
        )
    ]
